# Generated by Django 5.0.7 on 2024-07-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_id_post_content_alter_post_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Dj', 'Django'), ('Py', 'Python')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='SOME STRING', max_length=1024),
        ),
    ]
